version: '3.3'
services:
    test_db:
        command: postgres -c tcp_keepalives_idle=60 -c tcp_keepalives_interval=60 -c tcp_keepalives_count=60
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        image: postgis/postgis:12-3.0
        ports:
            - ${DB_PORT}:5432

    redis_cache:
        image: redis
        ports:
            - ${REDIS_PORT}:6379
        command: redis-server

    aws:
        image: localstack/localstack:latest
        ports:
            - ${AWS_LOCALSTACK_PORT}:4566
        environment:
            - SERVICES=s3,ssm,secretsmanager
            - DEBUG=1
            - DATA_DIR=/tmp/aws/data
